### PR TITLE
Added Debian requirements, make and g++

### PR DESCRIPTION
**Pull request by micahhausler**

### CODE REVIEW

**Comment by micahhausler** [comment]
@brianc is this still active?

**Comment by brianc** [comment]
Yes it's still active! Sorry - I think I had notifications turned off for this repo!  🤕  Turning them back on now!  Really apologize for this taking so long. :( I'll push a new patch version out here in just a min!.

**Comment by micahhausler** [comment]
Thanks!

**Comment by brianc** [comment]
Nah @micahhausler thank YOU! Sorry again for the delay. Notifications are turned back on! 💃

**Pull request merged**
